/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Maestro;

import Views.Administrador.*;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jorge Villanueva
 */
public class Ver_Materias extends javax.swing.JInternalFrame {

    /**
     * Creates new form Agregar_Alumno
     */
    public Ver_Materias() {
        
        initComponents();
       
        
           // this.setMaximum(true);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_encargado = new javax.swing.JComboBox();
        lblcontra5 = new javax.swing.JLabel();
        cmb_encargado1 = new javax.swing.JComboBox();
        lblcontra6 = new javax.swing.JLabel();
        lblcontra7 = new javax.swing.JLabel();
        cmb_encargado2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Asignar Maestro");
        setToolTipText("Asignar Maestro");
        setAlignmentX(0.0F);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(890, 408));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_encargado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "5", "6", "7", "8", "9" }));
        getContentPane().add(cmb_encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));

        lblcontra5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcontra5.setText("Grado:");
        getContentPane().add(lblcontra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        cmb_encargado1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lenguaje", "Matemáticas", "Ciencias Salud y Medio Ambiente", "Estudios Sociales", "Educacion Física", "Artistica", "Ingles" }));
        getContentPane().add(cmb_encargado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));

        lblcontra6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcontra6.setText("Materia:");
        getContentPane().add(lblcontra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lblcontra7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcontra7.setText("Sección:");
        getContentPane().add(lblcontra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        cmb_encargado2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        getContentPane().add(cmb_encargado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, -1));

        jButton1.setText("Mostrar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Maestro", "Grado", "Materia", "Sección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 800, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_encargado;
    private javax.swing.JComboBox cmb_encargado1;
    private javax.swing.JComboBox cmb_encargado2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcontra5;
    private javax.swing.JLabel lblcontra6;
    private javax.swing.JLabel lblcontra7;
    // End of variables declaration//GEN-END:variables
}
