/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Administrador;

import Acceso_Datos.AnhoJpaController;
import Acceso_Datos.ConectionDB;
import Acceso_Datos.MateriaJpaController;
import Acceso_Datos.entityMain;
import Logica_Negocios.Anho;
import Logica_Negocios.Materia;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Villanueva
 */
public class Crear_Materia extends javax.swing.JInternalFrame {

   MateriaJpaController Materia = new MateriaJpaController(entityMain.getInstance());
    
    public Crear_Materia() {
        
        initComponents();
        List<Materia> Materias = Materia.findMateriaEntities();
        for (Materia Materia1 : Materias) {
            cmb_anho.addItem(Materia1.getMateriaNombre());
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Btn_Guardar = new javax.swing.JButton();
        cmb_anho = new javax.swing.JComboBox();
        lblUsuario1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Materia");
        setToolTipText("Registrar Materia");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(343, 146));
        setMinimumSize(new java.awt.Dimension(343, 146));
        setPreferredSize(new java.awt.Dimension(343, 146));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setText("Año:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, 30));

        Btn_Guardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_Guardar.setText("Guardar");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, -1));

        getContentPane().add(cmb_anho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, -1));

        lblUsuario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario1.setText("Nombre:");
        getContentPane().add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        String anho = txtNombre.getText();
        String NombreM = cmb_anho.getSelectedItem().toString();
        
      
      BigDecimal id = null;
      if(NombreM.equals("Lenguaje")){
      id = new BigDecimal("1");
      }
      else if(NombreM.equals("Matemáticas")){
          id = new BigDecimal("2");
    }
      else if(NombreM.equals("Ciencia, Salud y Medio Ambiente")){
          id = new BigDecimal("3");
      }
      else if(NombreM.equals("Estudios Sociales")){
          id = new BigDecimal("4");
      }
      else if(NombreM.equals("Educación Fisica")){
          id = new BigDecimal("5");
      }
      else if(NombreM.equals("Educación Artistica")){
          id = new BigDecimal("6");
      }
      else if(NombreM.equals("Ingles")){
          id = new BigDecimal("7");
      }
      

        try {
           ConectionDB con = new ConectionDB();
           AnhoJpaController AnhoM = new AnhoJpaController(entityMain.getInstance());           
           Anho am = new Anho(con.GetIdToInsert("ANHO", "ID_ANHO"),anho);
           am.setMateriaIdMateria(new Materia(id, NombreM));
           AnhoM.create(am);
           JOptionPane.showMessageDialog(rootPane,"Se inserto con exito.." );
        } catch (Exception e) {
        }
      
    }//GEN-LAST:event_Btn_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JComboBox cmb_anho;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
