/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Administrador;

import Acceso_Datos.AlumnoJpaController;
import Acceso_Datos.entityMain;
import Logica_Negocios.Alumno;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Villanueva
 */
public class Editar_Alumno extends javax.swing.JInternalFrame {

   AlumnoJpaController CAlumno = new AlumnoJpaController(entityMain.getInstance());  
   String id="null";
  
    
    /**
     * Creates new form Agregar_Alumno
     */
    public Editar_Alumno() {
        
        initComponents();
       
       CargarTabla();
        
     Btn_Actualizar.enable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblcontra1 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_alumnos = new javax.swing.JTable();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblcontra = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        Btn_Actualizar = new javax.swing.JButton();
        lblcontra2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblcontra3 = new javax.swing.JLabel();
        dcc_fechaNac = new datechooser.beans.DateChooserCombo();
        lblcontra4 = new javax.swing.JLabel();
        txt_sex = new javax.swing.JTextField();
        btn_cmb_sex = new javax.swing.JButton();
        txt_activ = new javax.swing.JTextField();
        btn_cmb_estado = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        lblUsuario3 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        txtNie = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Alumno");
        setToolTipText("Editar Alumno");
        setAlignmentX(0.0F);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(890, 408));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setText("Nombre:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblcontra1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcontra1.setText("Direccion:");
        getContentPane().add(lblcontra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblUsuario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario1.setText("Telefono:");
        getContentPane().add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblUsuario2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario2.setText("Fecha Nacimiento:");
        getContentPane().add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        tabla_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Telefono", "Nie", "Direccion", "Fecha Nac.", "Genero", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_alumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla_alumnos.setAutoscrolls(false);
        tabla_alumnos.setFocusTraversalPolicyProvider(true);
        tabla_alumnos.setFocusable(false);
        tabla_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_alumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_alumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 72, 910, 630));

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, -1));

        txtDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, -1));

        lblcontra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcontra.setText("Apellido:");
        getContentPane().add(lblcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, -1));

        txtApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, -1));

        Btn_Actualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_Actualizar.setText("Actualizar");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 250, -1));

        lblcontra2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcontra2.setText("Genero:");
        getContentPane().add(lblcontra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Editar Alumno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 320, -1));

        lblcontra3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcontra3.setText("NIE:");
        getContentPane().add(lblcontra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        dcc_fechaNac.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dcc_fechaNac.setNothingAllowed(false);
    dcc_fechaNac.setFormat(2);
    dcc_fechaNac.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
    try {
        dcc_fechaNac.setForbiddenPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    dcc_fechaNac.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 18));
    dcc_fechaNac.setCurrentNavigateIndex(0);
    dcc_fechaNac.setShowOneMonth(true);
    getContentPane().add(dcc_fechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, -1));

    lblcontra4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    lblcontra4.setText("Estado:");
    getContentPane().add(lblcontra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

    txt_sex.setEditable(false);
    txt_sex.setText("Masculino");
    txt_sex.setAlignmentX(0.0F);
    txt_sex.setFocusable(false);
    txt_sex.setMargin(new java.awt.Insets(0, 0, 0, 0));
    getContentPane().add(txt_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 23));

    btn_cmb_sex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change.png"))); // NOI18N
    btn_cmb_sex.setMargin(new java.awt.Insets(0, 0, 0, 0));
    btn_cmb_sex.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_cmb_sexActionPerformed(evt);
        }
    });
    getContentPane().add(btn_cmb_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 30, 23));

    txt_activ.setEditable(false);
    txt_activ.setText("Activo");
    txt_activ.setFocusable(false);
    getContentPane().add(txt_activ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 160, -1));

    btn_cmb_estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change.png"))); // NOI18N
    btn_cmb_estado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_cmb_estadoActionPerformed(evt);
        }
    });
    getContentPane().add(btn_cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 29, -1));

    Btn_Limpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    Btn_Limpiar.setText("Limpiar");
    Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Btn_LimpiarActionPerformed(evt);
        }
    });
    getContentPane().add(Btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 250, -1));

    lblUsuario3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    lblUsuario3.setText("Id:");
    getContentPane().add(lblUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

    txt_Id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txt_Id.setEnabled(false);
    getContentPane().add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, -1));

    txtNie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    getContentPane().add(txtNie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, -1));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
        // TODO add your handling code here:
        try {
            if (!id.equals("null")) {
                
                String nombre=txtNombre.getText();
                String apellido=txtApellido.getText();
                String tel=txtTelefono.getText();
                String direcc=txtDireccion.getText();
                String nie =txtNie.getText();
                String date =dcc_fechaNac.getText();
                String genero=txt_sex.getText(); 
                String estado=txt_activ.getText();

                if (txt_sex.getText().equals("Masculino")) {
                    genero="1";
                }else{
                     genero="2";
                }
                if (txt_activ.getText().equals("Activo")) {
                    estado="1";
                }else{
                    estado="2";
                }
                Alumno alumno = new Alumno();   
                alumno.setIdAlumno(new BigDecimal(id));
                alumno.setAlumnoNombre(nombre);
                alumno.setAlumnoApelidos(apellido);
                alumno.setAlumnoDireccion(direcc);
                alumno.setAlumnoTel(tel);            
                alumno.setAlumnoNie(nie);
                alumno.setAlumnoFechaNac(new Date());
                alumno.setAlumnoGenero(new BigInteger(genero));
                alumno.setAlumnoEstado(new BigInteger(estado));                  
                CAlumno.edit(alumno);
                CargarTabla();
                JOptionPane.showMessageDialog(rootPane, "Alumno editado Correctamente");
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Algo salio mal.");
        }
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

    private void btn_cmb_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cmb_sexActionPerformed
        // TODO add your handling code here:
        String sex=txt_sex.getText();
        if (sex.equals("Masculino")) {
            txt_sex.setText("Femenino");
        }
        if (sex.equals("Femenino")) {
            txt_sex.setText("Masculino");
        }
    }//GEN-LAST:event_btn_cmb_sexActionPerformed

    private void btn_cmb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cmb_estadoActionPerformed
        // TODO add your handling code here:
        String estado=txt_activ.getText();
        if (estado.equals("Activo")) {
            txt_activ.setText("Inactivo");
        }
        if (estado.equals("Inactivo")) {
            txt_activ.setText("Activo");
        }
    }//GEN-LAST:event_btn_cmb_estadoActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        // TODO add your handling code here:
        id="null";
        txt_Id.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtNie.setText("");
    }//GEN-LAST:event_Btn_LimpiarActionPerformed
    
    private void tabla_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_alumnosMouseClicked
        // TODO add your handling code here:
        
        id = tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(), 0).toString();
        String nom=tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(), 1).toString();
        String ape=tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(), 2).toString();
        
        String tel=tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(),3).toString();
        String nie=tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(),4).toString();
        String dire=tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(), 5).toString();
        String fecha=tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(), 6).toString();
        String genero=tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(), 7).toString();
        String estado = tabla_alumnos.getValueAt(tabla_alumnos.getSelectedRow(), 8).toString();
        
        txt_Id.setText(id);
        txtNombre.setText(nom);
        txtApellido.setText(ape);
        txtDireccion.setText(dire);
        txtTelefono.setText(tel);
        txtNie.setText(nie);
        dcc_fechaNac.setText(fecha);
        
        
        if (genero.equals("1")) {
            txt_sex.setText("Masculino");
        }else{
            txt_sex.setText("Femenino");
        }
        if (estado.equals("1")) {
            txt_activ.setText("Activo");
        }else{
            txt_activ.setText("Inactivo");
        }
        
    }//GEN-LAST:event_tabla_alumnosMouseClicked
     private void CargarTabla() {        
        List<Alumno> lm = CAlumno.findAlumnoEntities();         
        DefaultTableModel modM = (DefaultTableModel) tabla_alumnos.getModel(); 
        modM.setRowCount(0);                
        for(int i=0; i<lm.size(); i++)
        {
            String[] registroC = {lm.get(i).getIdAlumno().toString(), 
                                  lm.get(i).getAlumnoNombre(),
                                  lm.get(i).getAlumnoApelidos(),
            lm.get(i).getAlumnoTel(),
            lm.get(i).getAlumnoNie(),
            lm.get(i).getAlumnoDireccion(),
            lm.get(i).getAlumnoFechaNac().toString(),
            lm.get(i).getAlumnoGenero().toString(),
            lm.get(i).getAlumnoEstado().toString()};
            modM.addRow(registroC);
        }          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton btn_cmb_estado;
    private javax.swing.JButton btn_cmb_sex;
    private datechooser.beans.DateChooserCombo dcc_fechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblcontra;
    private javax.swing.JLabel lblcontra1;
    private javax.swing.JLabel lblcontra2;
    private javax.swing.JLabel lblcontra3;
    private javax.swing.JLabel lblcontra4;
    private javax.swing.JTable tabla_alumnos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNie;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_activ;
    private javax.swing.JTextField txt_sex;
    // End of variables declaration//GEN-END:variables
}
