/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Administrador;

import Acceso_Datos.AnhoJpaController;
import Acceso_Datos.entityMain;
import Logica_Negocios.Anho;
import Logica_Negocios.Materia;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Villanueva
 */
public class Editar_Materia extends javax.swing.JInternalFrame {

    String id="null";
    AnhoJpaController Anhoo = new AnhoJpaController(entityMain.getInstance());
    public Editar_Materia() {
        
        initComponents();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_anho = new javax.swing.JTextField();
        Btn_Actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btn_Limpiar = new javax.swing.JButton();
        lblUsuario3 = new javax.swing.JLabel();
        txt_materia = new javax.swing.JTextField();
        lblUsuario4 = new javax.swing.JLabel();
        txt_Id1 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Materia");
        setToolTipText("Editar Materia");
        setAlignmentX(0.0F);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(890, 408));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setText("Materia:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Materia", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoscrolls(false);
        jTable1.setFocusTraversalPolicyProvider(true);
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 72, 910, 630));

        txt_anho.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txt_anho, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, -1));

        Btn_Actualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_Actualizar.setText("Actualizar");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 200, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Editar Materia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 320, -1));

        Btn_Limpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, -1));

        lblUsuario3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario3.setText("Id:");
        getContentPane().add(lblUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        txt_materia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_materia.setEnabled(false);
        getContentPane().add(txt_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, -1));

        lblUsuario4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario4.setText("Año:");
        getContentPane().add(lblUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 20));

        txt_Id1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_Id1.setEnabled(false);
        getContentPane().add(txt_Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
       id="null";
        txt_Id1.setText("");
        txt_materia.setText("");
        txt_anho.setText("");
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
      String NombreM = txt_materia.getText();

      BigDecimal idM = null;
      if(NombreM.equals("Lenguaje")){
      idM = new BigDecimal("1");
      }
      else if(NombreM.equals("Matemáticas")){
          idM = new BigDecimal("2");
    }
      else if(NombreM.equals("Ciencia, Salud y Medio Ambiente")){
          idM = new BigDecimal("3");
      }
      else if(NombreM.equals("Estudios Sociales")){
          idM = new BigDecimal("4");
      }
      else if(NombreM.equals("Educación Fisica")){
          idM = new BigDecimal("5");
      }
      else if(NombreM.equals("Educación Artistica")){
          idM = new BigDecimal("6");
      }
      else if(NombreM.equals("Ingles")){
          idM = new BigDecimal("7");
      } 
        try {
            if(!id.equals("null")){
                String anhou = txt_anho.getText();
                Anho am = new Anho();
                am.setAnho(anhou);
                am.setIdAnho(new BigDecimal(id));
                am.setMateriaIdMateria(new Materia(idM,NombreM));
                Anhoo.edit(am);
            CargarTabla();
                JOptionPane.showMessageDialog(null, "Materia Editada Correctamente");
            }            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Algo salio mal.");
        }
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

     
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        id=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String materia=jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String anho=jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        
        txt_Id1.setText(id);
        txt_materia.setText(materia);
        txt_anho.setText(anho);
    }//GEN-LAST:event_jTable1MouseClicked
    private void CargarTabla() {        
        List<Anho> lm = Anhoo.findAnhoEntities();         
        DefaultTableModel modM = (DefaultTableModel) jTable1.getModel(); 
        modM.setRowCount(0);                
        for(int i=0; i<lm.size(); i++)
        {
            String[] registroC = {lm.get(i).getIdAnho().toString(), 
                                  lm.get(i).getMateriaIdMateria().getMateriaNombre(),
                                  lm.get(i).getAnho()};
            modM.addRow(registroC);
        }          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JTextField txt_Id1;
    private javax.swing.JTextField txt_anho;
    private javax.swing.JTextField txt_materia;
    // End of variables declaration//GEN-END:variables
    
}
