/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Administrador;

import Acceso_Datos.AnhoJpaController;
import Acceso_Datos.ConectionDB;
import Acceso_Datos.DocenteJpaController;
import Acceso_Datos.GradoJpaController;
import Acceso_Datos.MateriaGradoJpaController;
import Acceso_Datos.MateriaJpaController;
import Acceso_Datos.SeccionJpaController;
import Acceso_Datos.TurnoJpaController;
import Acceso_Datos.entityMain;
import Logica_Negocios.Anho;
import Logica_Negocios.Docente;
import Logica_Negocios.Grado;
import Logica_Negocios.Materia;
import Logica_Negocios.MateriaGrado;
import Logica_Negocios.Seccion;
import Logica_Negocios.Turno;
import Reportes.GenerarReportes;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Villanueva
 */
public class Reporte_MateriasAsignadas extends javax.swing.JInternalFrame {

    String id="null";
    AnhoJpaController Anhoo = new AnhoJpaController(entityMain.getInstance());
    MateriaGradoJpaController MateriaGradoJpaController = new MateriaGradoJpaController(entityMain.getInstance());
    MateriaGradoJpaController materiaGradoJpaController = new MateriaGradoJpaController(entityMain.getInstance());
    MateriaJpaController materiaJpaController = new MateriaJpaController(entityMain.getInstance());
    GradoJpaController gjc = new GradoJpaController(entityMain.getInstance());
    SeccionJpaController sjc = new SeccionJpaController(entityMain.getInstance());
    TurnoJpaController tjc = new TurnoJpaController(entityMain.getInstance());
    DocenteJpaController djc = new DocenteJpaController(entityMain.getInstance());
    MateriaJpaController mjc = new MateriaJpaController(entityMain.getInstance());
    ConectionDB con = new ConectionDB(); 
    public Reporte_MateriasAsignadas() {
        
        initComponents();
        cargartabla();
//        LLenarComboM(); 
//        LLenarComboS(); 
//        LLenarComboG(); 
//        LLenarComboT(); 
        LLenarComboD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Btn_GenerarReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmb_docente = new javax.swing.JComboBox();
        lblUsuario6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte Materias");
        setToolTipText("Editar Materia");
        setAlignmentX(0.0F);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(890, 408));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Materia", "Grado", "Seccion", "Turno", "Año", "Docente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoscrolls(false);
        jTable1.setFocusTraversalPolicyProvider(true);
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 72, 910, 630));

        Btn_GenerarReporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btn_GenerarReporte.setText("Generar Reporte");
        Btn_GenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_GenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 210, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Reporte Asignación de Materias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 560, -1));

        getContentPane().add(cmb_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 210, -1));

        lblUsuario6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario6.setText("Docente:");
        getContentPane().add(lblUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_GenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GenerarReporteActionPerformed

     String docente = cmb_docente.getSelectedItem().toString();
     GenerarReportes gr = new GenerarReportes();
     gr.ReporteMateria(docente);
    }//GEN-LAST:event_Btn_GenerarReporteActionPerformed

     
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
//        id=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
//        txt_id.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
//        String materia=jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
//        String grado=jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
//        String seccion=jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
//        String turno=jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
//        String anho=jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
//        String docente=jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
  
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void cargartabla(){
    
    List<MateriaGrado>lmm =  MateriaGradoJpaController.findMateriaGradoEntities();
    DefaultTableModel modM = (DefaultTableModel) jTable1.getModel(); 
    modM.setRowCount(0);
    for(int i=0; i<lmm.size(); i++)
        {
            String[] registroC = {lmm.get(i).getIdMateriaGrado().toString(),
                                  lmm.get(i).getIdMateria().getMateriaNombre(),
                                  lmm.get(i).getIdGrado().getGrado(),
                                  lmm.get(i).getIdSeccion().getNombreSeccion(),
                                  lmm.get(i).getIdTurno().getTurnoNombre(),
                                  lmm.get(i).getAnho().toString(),
                                  lmm.get(i).getIdDocente().getDocenteNombre()};
              modM.addRow(registroC);
           }
          
        }
    private void LLenarComboD() {
        List<Docente> docentes = djc.findDocenteEntities();
        for (Docente docente : docentes) {
           if (docente.getDocenteEstado().equals("Activo")) {
              cmb_docente.addItem(docente.getDocenteNombre() +" " + docente.getDocenteApellido());   
            } 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_GenerarReporte;
    private javax.swing.JComboBox cmb_docente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUsuario6;
    // End of variables declaration//GEN-END:variables

}
